<a href="https://colab.research.google.com/github/PrasantIITM/ma22c033_2023_PL/blob/main/Assignment%208/Null_space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
from scipy.linalg import svd, qr
A = np.array([[1, -2, 9, 5, 4,], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2],[4, 1, 9, 1, -9]])
A

array([[ 1, -2,  9,  5,  4],
       [ 1, -1,  6,  5, -3],
       [-2,  0, -6,  1, -2],
       [ 4,  1,  9,  1, -9]])

**Task 1**                                                                    

The null space of the given matrix A using SVD.

From Svd we can say a basis for the nullspace is the column vectors of the matrix V from rth column to nth column . where r is the rank of A.

In [36]:
u,s,vT=svd(A)

In [37]:
vT

array([[ 0.24638127, -0.04503456,  0.8742475 ,  0.30107333, -0.28690474],
       [-0.12991821, -0.20626881,  0.22905181,  0.27058334,  0.90271499],
       [ 0.3027347 ,  0.2022255 ,  0.3015276 , -0.84037193,  0.26516538],
       [-0.87219483,  0.3573579 ,  0.29073161, -0.14709627, -0.07354813],
       [ 0.26466093,  0.8870317 , -0.08822031,  0.32905504,  0.16452752]])

In [38]:
r_vT = np.linalg.matrix_rank(A)
r_vT

3

In [56]:
for i in range(4):
  if np.linalg.matrix_rank(A)+i <= 4:
    print("b{}".format(i+1),vT.T[:,r_vT+i],end=" ")        # basis vectors for nullspace
    print("Ab{}=".format(i+1),A @ vT.T[:,r_vT+i])       #verify the basis vector

b1 [-0.87219483  0.3573579   0.29073161 -0.14709627 -0.07354813] Ab1= [-1.66533454e-15 -4.35762537e-15 -4.77395901e-15  2.02615702e-15]
b2 [ 0.26466093  0.8870317  -0.08822031  0.32905504  0.16452752] Ab2= [ 8.88178420e-16  1.66533454e-16 -1.11022302e-15  5.55111512e-16]


as A @ vT.T[:,r_vT+i+1] is close to 0 so [ 0.26466093  0.8870317  -0.08822031  0.32905504  0.16452752] is a basis for null space pf A

**Task 2**

As A= QR and Q is full rank so nullspace of A= nullspace R

In [41]:
Q,R=qr(A)

In [43]:
S,D,V=svd(R)

In [45]:
r_R = np.linalg.matrix_rank(R)
r_R

3

In [57]:
for i in range(4):
  if np.linalg.matrix_rank(A)+i <= 4:
    print(V.T[:,r_R+i],end=" ")


[-0.82775801 -0.32212404  0.27591934 -0.32853773 -0.16426886] [ 0.38155721 -0.90042546 -0.12718574 -0.14824807 -0.07412404] 

In [58]:
sq=np.array(([-0.82775801, -0.32212404,  0.27591934, -0.32853773, -0.16426886],   # matrix of the both basis
 [ 0.38155721, -0.90042546, -0.12718574, -0.14824807, -0.07412404],
  [-0.87219483,  0.3573579,   0.29073161, -0.14709627, -0.07354813],
   [ 0.26466093,  0.8870317,  -0.08822031,  0.32905504,  0.16452752]))
sq

array([[-0.82775801, -0.32212404,  0.27591934, -0.32853773, -0.16426886],
       [ 0.38155721, -0.90042546, -0.12718574, -0.14824807, -0.07412404],
       [-0.87219483,  0.3573579 ,  0.29073161, -0.14709627, -0.07354813],
       [ 0.26466093,  0.8870317 , -0.08822031,  0.32905504,  0.16452752]])

In [48]:
np.linalg.matrix_rank(sq)

4

 from above we can conclude that both null space are not equal. as one can't  span other.